services:
  - type: web
    name: floor-visualizer-ai
    env: python
        pythonVersion: 3.11
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300
    envVars:
      - key: OPENAI_API_KEY
        sync: false
